name: Dependabot Auto-Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  dependabot-automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Require label "automerge"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number
            });

            const hasLabel = labels.data.some(label => label.name === 'automerge');
            if (!hasLabel) {
              core.setFailed('Label "automerge" is required for auto-merge.');
            }

      - name: Wait for required status checks
        uses: WyriHaximus/github-action-wait-for-status@v1
        with:
          ignoreActions: 'dependabot-automerge'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: "automerge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "60000"
          UPDATE_METHOD: "merge"
